{% set name = "sphinxcontrib-bibtex" %}
{% set version = "2.6.4" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  fn: {{ name }}-{{ version }}.tar.gz
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ name.replace('-', '_') }}-{{ version }}.tar.gz
  sha256: aad018b730d324201f09777f6c25c4a2ff7ac1d5e66af187f21fc21840768760

build:
  noarch: python
  number: 0
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation

requirements:
  host:
    - pip
    - python {{ python_min }}
    - setuptools
    - docutils >=0.8,!=0.18.*,!=0.19.*
    - pybtex >=0.24
    - pybtex-docutils >=1
    - sphinx >=3.5
    - importlib-metadata >=3.6
  run:
    - setuptools
    - python >={{ python_min }}
    - docutils >=0.8,!=0.18.*,!=0.19.*
    - pybtex >=0.24
    - pybtex-docutils >=1.0.0
    - sphinx >=3.5
    - importlib-metadata >=3.6

test:
  requires:
    - pip
    - python {{ python_min }}
  imports:
    - sphinxcontrib
    - sphinxcontrib.bibtex
  commands:
    - pip check

about:
  home: https://github.com/mcmtroffaes/sphinxcontrib-bibtex
  license: BSD-2-Clause
  license_family: BSD
  license_file: LICENSE.rst
  summary: A Sphinx extension for BibTeX style citations.
  description: This extension allows BibTeX citations to be inserted into documentation generated by Sphinx."
  doc_url: http://sphinxcontrib-bibtex.readthedocs.org/en/latest/
  dev_url: https://github.com/mcmtroffaes/sphinxcontrib-bibtex/

extra:
  recipe-maintainers:
    - conda-forge/sphinx
    - croth1
