{% set name = "sphinxcontrib-bibtex" %}
{% set version = "2.6.1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  fn: {{ name }}-{{ version }}.tar.gz
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 046b49f070ae5276af34c1b8ddb9bc9562ef6de2f7a52d37a91cb8e53f54b863

build:
  noarch: python
  number: 1
  script: {{ PYTHON }} -m pip install . --no-deps -vv

requirements:
  host:
    - pip
    - python >=3.7
    - setuptools
    - docutils >=0.8,!=0.18.*,!=0.19.*
    - pybtex >=0.24
    - pybtex-docutils >=1
    - sphinx >=3.5
    - dataclasses  # can be removed when cf drops py3.6 support
    - importlib_metadata >=3.6
  run:
    - python >=3.7
    - docutils >=0.8,!=0.18.*,!=0.19.*
    - pybtex >=0.24
    - pybtex-docutils >=1
    - sphinx >=3.5
    - dataclasses  # can be removed when cf drops py3.6 support
    - importlib_metadata >=3.6

test:
  requires:
    - pip
  imports:
    - sphinxcontrib
    - sphinxcontrib.bibtex
  commands:
    - pip check

about:
  home: https://github.com/mcmtroffaes/sphinxcontrib-bibtex
  license: BSD-2-Clause
  license_family: BSD
  license_file: LICENSE.rst
  summary: A Sphinx extension for BibTeX style citations.
  description: This extension allows BibTeX citations to be inserted into documentation generated by Sphinx."
  doc_url: http://sphinxcontrib-bibtex.readthedocs.org/en/latest/
  dev_url: https://github.com/mcmtroffaes/sphinxcontrib-bibtex/

extra:
  recipe-maintainers:
    - conda-forge/sphinx
    - croth1
